export type Post = {
  id: number;
  userId: string;
  displayName: string;
  userName: string;
  emailVerified: boolean;
  avatar: string;
  type: "tweet" | "replay" | "retweet";
  public: boolean;
  content: string;
  image: string;
  replay: number;
  retweet: number;
  likes: number;
  replayIds?: string;
  retweetIds?: string;
  likesIds?: string;
  replayTo: number;
  retweetBy?: string;
  authUserId?: string;
  authUserName?: string;
  created_at: string;
  updated_at: string;
};

export type SendPost = {
  userId: string;
  displayName: string;
  userName: string;
  emailVerified: boolean;
  avatar: string;
  type: "tweet" | "replay";
  public: boolean;
  content: string;
  image: string;
  replay: number;
  retweet: number;
  likes: number;
  replayIds?: string;
  retweetIds?: string;
  likesIds?: string;
  replayTo: number;
  retweetBy?: string;
};
